version: "3.4"
services:
  openstead-api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV:-production}
        - UID=1000
        - GID=1000
    environment:
      - UID=1000
      - GID=1000
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: openstead-api
    image: openstead-api
    ports:
      - 8000:8000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - openstead-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=openstead
      - MYSQL_USER=openstead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 33062:3306
  redis:
    image: redis
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - openstead-minio:/data
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-Password123}
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set osminio http://minio:9000 ${MINIO_USER:-minio} ${MINIO_PASSWORD:-Password123};
      /usr/bin/mc mb osminio/images;
      /usr/bin/mc policy set public osminio/images;
      exit 0;
      "

volumes:
  openstead-mysql:
  openstead-minio: { }