name: Frontend Docker Image Build and Push

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --tag ${{ secrets.REGISTRY_URL }}/openstead-frontend:${{ github.sha }} .
      working-directory: ./frontend

    - name: Login to Docker Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.REGISTRY_URL }}/openstead-frontend:${{ github.sha }}
        docker tag ${{ secrets.REGISTRY_URL }}/openstead-frontend:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/openstead-frontend:latest
        docker push ${{ secrets.REGISTRY_URL }}/openstead-frontend:latest
